
// This file has been generated by the GUI designer. Do not modify.
namespace TatooineDesktop
{
	public partial class ArchiveWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TatooineDesktop.ArchiveWindow
			this.Name = "TatooineDesktop.ArchiveWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ArchiveWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
