#!/bin/bash

# Build script for common lib
echo "Building Lib..."
echo "-----------------------------"

# Current path
CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

dmcs -t:library -out:$CWD/Tatooine.common.dll -unsafe "$CWD/*.cs"
