
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame1;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label GtkLabel;
	private global::Gtk.Label label1;
	private global::Gtk.Entry fileEntry;
	private global::Gtk.Button button2;
	private global::Gtk.Button button1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkLabel = new global::Gtk.Label ();
		this.GtkLabel.Name = "GtkLabel";
		this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Load from file</b>");
		this.GtkLabel.UseMarkup = true;
		this.fixed1.Add (this.GtkLabel);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkLabel]));
		w1.X = 10;
		w1.Y = 2;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("From file:");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w2.X = 44;
		w2.Y = 29;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.fileEntry = new global::Gtk.Entry ();
		this.fileEntry.WidthRequest = 350;
		this.fileEntry.CanFocus = true;
		this.fileEntry.Name = "fileEntry";
		this.fileEntry.IsEditable = true;
		this.fileEntry.InvisibleChar = '●';
		this.fixed1.Add (this.fileEntry);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.fileEntry]));
		w3.X = 108;
		w3.Y = 21;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Choose");
		this.fixed1.Add (this.button2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button2]));
		w4.X = 464;
		w4.Y = 22;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Open");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w5.X = 477;
		w5.Y = 57;
		this.frame1.Add (this.fixed1);
		this.Add (this.frame1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 546;
		this.DefaultHeight = 295;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler (this.chooseClicked);
		this.button1.Clicked += new global::System.EventHandler (this.openClicked);
	}
}
