
// This file has been generated by the GUI designer. Do not modify.
namespace Tatooine
{
	public partial class ArchiveWindow
	{
		private global::Gtk.HBox hbox1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Tatooine.ArchiveWindow
			this.Name = "Tatooine.ArchiveWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ArchiveWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Tatooine.ArchiveWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 680;
			this.DefaultHeight = 443;
			this.Show ();
		}
	}
}
