#!/bin/bash

# Build script for core library
echo "Building core..."
echo "-----------------------------"

# Current path
CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CORE_PATH="$CWD/core"
BUILD_PATH="$CWD/build"

if [ -e "$BUILD_PATH/Tatooine.core.dll" ]; then
	rm "$BUILD_PATH/Tatooine.core.dll"
fi
dmcs -t:library -out:"$BUILD_PATH/Tatooine.core.dll" -unsafe "$CORE_PATH/*.cs"
